version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword 
    volumes:
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5432:5432"
    networks:
      - postgres-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "kaiohenriqueps@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Password!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network
networks: 
  postgres-network:
    driver: bridge